include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Dart Style
    - prefer_single_quotes
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations
    - avoid_print
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
    - use_key_in_widget_constructors
    
    # Best Practices
    - always_declare_return_types
    - avoid_empty_else
    - avoid_returning_null_for_void
    - cancel_subscriptions
    - close_sinks
    - no_duplicate_case_values
    - prefer_is_empty
    - prefer_is_not_empty
    - unnecessary_this

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  
  errors:
    invalid_annotation_target: ignore
