// Mocks generated by Mockito 5.4.6 from annotations
// in matzo/test/presentation/category/bloc/category_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:matzo/domain/entities/todo_item.dart' as _i5;
import 'package:matzo/domain/repositories/todo_item_repository.dart' as _i2;
import 'package:matzo/domain/usecases/todo_item/add_todo_item.dart' as _i6;
import 'package:matzo/domain/usecases/todo_item/delete_todo_item.dart' as _i11;
import 'package:matzo/domain/usecases/todo_item/get_todo_items.dart' as _i3;
import 'package:matzo/domain/usecases/todo_item/toggle_todo_item.dart' as _i7;
import 'package:matzo/domain/usecases/todo_item/update_item_count.dart' as _i8;
import 'package:matzo/domain/usecases/todo_item/update_item_order.dart' as _i9;
import 'package:matzo/domain/usecases/todo_item/update_todo_item.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTodoItemRepository_0 extends _i1.SmartFake
    implements _i2.TodoItemRepository {
  _FakeTodoItemRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetTodoItems].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTodoItems extends _i1.Mock implements _i3.GetTodoItems {
  MockGetTodoItems() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TodoItemRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTodoItemRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TodoItemRepository);

  @override
  _i4.Future<List<_i5.TodoItem>> call(int? categoryId) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [categoryId],
        ),
        returnValue: _i4.Future<List<_i5.TodoItem>>.value(<_i5.TodoItem>[]),
      ) as _i4.Future<List<_i5.TodoItem>>);
}

/// A class which mocks [AddTodoItem].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddTodoItem extends _i1.Mock implements _i6.AddTodoItem {
  MockAddTodoItem() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TodoItemRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTodoItemRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TodoItemRepository);

  @override
  _i4.Future<int> call({
    required int? categoryId,
    required String? title,
    int? count = 1,
    int? order = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #categoryId: categoryId,
            #title: title,
            #count: count,
            #order: order,
          },
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
}

/// A class which mocks [ToggleTodoItem].
///
/// See the documentation for Mockito's code generation for more information.
class MockToggleTodoItem extends _i1.Mock implements _i7.ToggleTodoItem {
  MockToggleTodoItem() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TodoItemRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTodoItemRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TodoItemRepository);

  @override
  _i4.Future<void> call(int? itemId) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [itemId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [UpdateItemCount].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateItemCount extends _i1.Mock implements _i8.UpdateItemCount {
  MockUpdateItemCount() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TodoItemRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTodoItemRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TodoItemRepository);

  @override
  _i4.Future<void> call(
    int? itemId,
    int? newCount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            itemId,
            newCount,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [UpdateItemOrder].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateItemOrder extends _i1.Mock implements _i9.UpdateItemOrder {
  MockUpdateItemOrder() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TodoItemRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTodoItemRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TodoItemRepository);

  @override
  _i4.Future<void> call(
    int? itemId,
    int? newOrder,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            itemId,
            newOrder,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [UpdateTodoItem].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateTodoItem extends _i1.Mock implements _i10.UpdateTodoItem {
  MockUpdateTodoItem() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TodoItemRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTodoItemRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TodoItemRepository);

  @override
  _i4.Future<void> call({
    required _i5.TodoItem? item,
    String? newTitle,
    int? newCount,
    String? description,
    List<String>? links,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #item: item,
            #newTitle: newTitle,
            #newCount: newCount,
            #description: description,
            #links: links,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [DeleteTodoItem].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteTodoItem extends _i1.Mock implements _i11.DeleteTodoItem {
  MockDeleteTodoItem() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TodoItemRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTodoItemRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TodoItemRepository);

  @override
  _i4.Future<void> call(int? itemId) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [itemId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
