// Mocks generated by Mockito 5.4.6 from annotations
// in matzo/test/domain/usecases/todo_item/toggle_todo_item_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:matzo/domain/entities/todo_item.dart' as _i4;
import 'package:matzo/domain/repositories/todo_item_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TodoItemRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoItemRepository extends _i1.Mock
    implements _i2.TodoItemRepository {
  MockTodoItemRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.TodoItem>> getItemsByCategory(int? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemsByCategory,
          [categoryId],
        ),
        returnValue: _i3.Future<List<_i4.TodoItem>>.value(<_i4.TodoItem>[]),
      ) as _i3.Future<List<_i4.TodoItem>>);

  @override
  _i3.Future<_i4.TodoItem?> getItemById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getItemById,
          [id],
        ),
        returnValue: _i3.Future<_i4.TodoItem?>.value(),
      ) as _i3.Future<_i4.TodoItem?>);

  @override
  _i3.Future<int> addItem(_i4.TodoItem? item) => (super.noSuchMethod(
        Invocation.method(
          #addItem,
          [item],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> updateItem(_i4.TodoItem? item) => (super.noSuchMethod(
        Invocation.method(
          #updateItem,
          [item],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteItem(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteItem,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> toggleItemCompletion(int? id) => (super.noSuchMethod(
        Invocation.method(
          #toggleItemCompletion,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateItemCount(
    int? id,
    int? newCount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateItemCount,
          [
            id,
            newCount,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateItemOrder(
    int? id,
    int? newOrder,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateItemOrder,
          [
            id,
            newOrder,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
