// Mocks generated by Mockito 5.4.6 from annotations
// in matzo/test/presentation/home/bloc/home_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:matzo/domain/entities/category.dart' as _i6;
import 'package:matzo/domain/entities/todo_item.dart' as _i11;
import 'package:matzo/domain/repositories/category_repository.dart' as _i2;
import 'package:matzo/domain/repositories/todo_item_repository.dart' as _i3;
import 'package:matzo/domain/usecases/category/add_category.dart' as _i7;
import 'package:matzo/domain/usecases/category/delete_category.dart' as _i8;
import 'package:matzo/domain/usecases/category/get_categories.dart' as _i4;
import 'package:matzo/domain/usecases/category/get_category_item_count.dart'
    as _i9;
import 'package:matzo/domain/usecases/todo_item/get_todo_items.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCategoryRepository_0 extends _i1.SmartFake
    implements _i2.CategoryRepository {
  _FakeCategoryRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTodoItemRepository_1 extends _i1.SmartFake
    implements _i3.TodoItemRepository {
  _FakeTodoItemRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetCategories].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCategories extends _i1.Mock implements _i4.GetCategories {
  MockGetCategories() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CategoryRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCategoryRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CategoryRepository);

  @override
  _i5.Future<List<_i6.Category>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Future<List<_i6.Category>>.value(<_i6.Category>[]),
      ) as _i5.Future<List<_i6.Category>>);
}

/// A class which mocks [AddCategory].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddCategory extends _i1.Mock implements _i7.AddCategory {
  MockAddCategory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CategoryRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCategoryRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CategoryRepository);

  @override
  _i5.Future<int> call(
    String? name, {
    int? iconCodePoint,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [name],
          {#iconCodePoint: iconCodePoint},
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);
}

/// A class which mocks [DeleteCategory].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteCategory extends _i1.Mock implements _i8.DeleteCategory {
  MockDeleteCategory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CategoryRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCategoryRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CategoryRepository);

  @override
  _i5.Future<void> call(int? categoryId) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [categoryId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [GetCategoryItemCount].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCategoryItemCount extends _i1.Mock
    implements _i9.GetCategoryItemCount {
  MockGetCategoryItemCount() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CategoryRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCategoryRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CategoryRepository);

  @override
  _i5.Future<int> call(int? categoryId) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [categoryId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);
}

/// A class which mocks [GetTodoItems].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTodoItems extends _i1.Mock implements _i10.GetTodoItems {
  MockGetTodoItems() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TodoItemRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTodoItemRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.TodoItemRepository);

  @override
  _i5.Future<List<_i11.TodoItem>> call(int? categoryId) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [categoryId],
        ),
        returnValue: _i5.Future<List<_i11.TodoItem>>.value(<_i11.TodoItem>[]),
      ) as _i5.Future<List<_i11.TodoItem>>);
}
