// Mocks generated by Mockito 5.4.6 from annotations
// in matzo/test/presentation/home/bloc/home_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:matzo/domain/entities/category.dart' as _i5;
import 'package:matzo/domain/repositories/category_repository.dart' as _i2;
import 'package:matzo/domain/usecases/category/add_category.dart' as _i7;
import 'package:matzo/domain/usecases/category/delete_category.dart' as _i9;
import 'package:matzo/domain/usecases/category/get_recursive_item_count.dart'
    as _i10;
import 'package:matzo/domain/usecases/category/get_recursive_total_item_count.dart'
    as _i11;
import 'package:matzo/domain/usecases/category/get_subcategories.dart' as _i6;
import 'package:matzo/domain/usecases/category/get_top_level_categories.dart'
    as _i3;
import 'package:matzo/domain/usecases/category/reorder_categories.dart' as _i12;
import 'package:matzo/domain/usecases/category/update_category.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCategoryRepository_0 extends _i1.SmartFake
    implements _i2.CategoryRepository {
  _FakeCategoryRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetTopLevelCategories].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTopLevelCategories extends _i1.Mock
    implements _i3.GetTopLevelCategories {
  MockGetTopLevelCategories() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CategoryRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCategoryRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CategoryRepository);

  @override
  _i4.Future<List<_i5.Category>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Category>>.value(<_i5.Category>[]),
      ) as _i4.Future<List<_i5.Category>>);
}

/// A class which mocks [GetSubcategories].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSubcategories extends _i1.Mock implements _i6.GetSubcategories {
  MockGetSubcategories() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CategoryRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCategoryRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CategoryRepository);

  @override
  _i4.Future<List<_i5.Category>> call(int? parentCategoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [parentCategoryId],
        ),
        returnValue: _i4.Future<List<_i5.Category>>.value(<_i5.Category>[]),
      ) as _i4.Future<List<_i5.Category>>);
}

/// A class which mocks [AddCategory].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddCategory extends _i1.Mock implements _i7.AddCategory {
  MockAddCategory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CategoryRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCategoryRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CategoryRepository);

  @override
  _i4.Future<int> call(
    String? name, {
    int? iconCodePoint,
    int? parentCategoryId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [name],
          {
            #iconCodePoint: iconCodePoint,
            #parentCategoryId: parentCategoryId,
          },
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
}

/// A class which mocks [UpdateCategory].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateCategory extends _i1.Mock implements _i8.UpdateCategory {
  MockUpdateCategory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CategoryRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCategoryRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CategoryRepository);

  @override
  _i4.Future<void> call({
    required int? categoryId,
    required String? newName,
    int? newIconCodePoint,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #categoryId: categoryId,
            #newName: newName,
            #newIconCodePoint: newIconCodePoint,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [DeleteCategory].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteCategory extends _i1.Mock implements _i9.DeleteCategory {
  MockDeleteCategory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CategoryRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCategoryRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CategoryRepository);

  @override
  _i4.Future<void> call(int? categoryId) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [categoryId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [GetRecursiveItemCount].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRecursiveItemCount extends _i1.Mock
    implements _i10.GetRecursiveItemCount {
  MockGetRecursiveItemCount() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CategoryRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCategoryRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CategoryRepository);

  @override
  _i4.Future<int> call(int? categoryId) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [categoryId],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
}

/// A class which mocks [GetRecursiveTotalItemCount].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRecursiveTotalItemCount extends _i1.Mock
    implements _i11.GetRecursiveTotalItemCount {
  MockGetRecursiveTotalItemCount() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CategoryRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCategoryRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CategoryRepository);

  @override
  _i4.Future<int> call(int? categoryId) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [categoryId],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
}

/// A class which mocks [ReorderCategories].
///
/// See the documentation for Mockito's code generation for more information.
class MockReorderCategories extends _i1.Mock implements _i12.ReorderCategories {
  MockReorderCategories() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CategoryRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCategoryRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CategoryRepository);

  @override
  _i4.Future<void> call(List<_i5.Category>? categories) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [categories],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
